[vc_row full_width="stretch_row" el_class="wph-secondary-bg"][vc_column][vc_empty_space height="50px" el_class="hidden-xs"][/vc_column][/vc_row][vc_row full_width="stretch_row" el_class="wph-secondary-bg"][vc_column][vc_column_text]Hey! To make this page look awesome, apply this custom CSS code to that page via cog icon on the top of visual editor:
<pre>/* proper alignment for buttons in last section */
.vertical-align-initial .btn { vertical-align: initial; margin: 0 15px; }
.media-xs .vertical-align-initial { margin-top: -15px; }
.media-xs .vertical-align-initial .btn { margin-top: 15px; }

.wph-small-socials a { font-size: 16px; }</pre>
[/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1467829581743{padding-top: 50px !important;padding-bottom: 20px !important;}" el_class="wph-secondary-bg"][vc_column width="5/12" css=".vc_custom_1467551233181{margin-bottom: 30px !important;}" offset="vc_col-lg-offset-2 vc_col-lg-4 vc_col-md-offset-1 vc_col-md-5 vc_col-sm-offset-1"][contact-form-7 id="731"][/vc_column][vc_column width="5/12" offset="vc_col-md-offset-2 vc_col-md-4 vc_col-sm-offset-1" css=".vc_custom_1467551239155{margin-bottom: 30px !important;}"][vc_custom_heading text="SOCIAL ICONS" font_container="tag:div|font_size:12px|text_align:left|color:%23888888|line_height:1" use_theme_fonts="yes" css=".vc_custom_1467459087483{margin-bottom: 10px !important;}" el_class="wph-secondary-font"][wph_jo_socials_widget socials="Facebook : #
Gplus: #
Twitter : #
Rss : #" align="align_left" el_class="wph-small-socials" css=".vc_custom_1467459162529{margin-bottom: 30px !important;}"][vc_custom_heading text="CALL US" font_container="tag:div|font_size:12px|text_align:left|color:%23888888|line_height:1" use_theme_fonts="yes" css=".vc_custom_1467459092027{margin-bottom: 10px !important;}" el_class="wph-secondary-font"][wph_jo_styled_textbox font_family="wph-secondary-font" custom_color="#000000" css=".vc_custom_1467459285889{margin-bottom: 40px !important;}"](734) 393-9904[/wph_jo_styled_textbox][vc_custom_heading text="E-MAIL" font_container="tag:div|font_size:12px|text_align:left|color:%23888888|line_height:1" use_theme_fonts="yes" css=".vc_custom_1467459104391{margin-bottom: 10px !important;}" el_class="wph-secondary-font"][wph_jo_styled_textbox font_family="wph-secondary-font" custom_color="#000000" css=".vc_custom_1467459290401{margin-bottom: 40px !important;}"]contact@mail.co[/wph_jo_styled_textbox][vc_custom_heading text="VISIT US" font_container="tag:div|font_size:12px|text_align:left|color:%23888888|line_height:1" use_theme_fonts="yes" css=".vc_custom_1467459101263{margin-bottom: 10px !important;}" el_class="wph-secondary-font"][wph_jo_styled_textbox font_family="wph-secondary-font" custom_color="#000000" css=".vc_custom_1467459299905{margin-bottom: 40px !important;}"]801 Everardo
Burgs Suite 033[/wph_jo_styled_textbox][vc_custom_heading text="VISIT US" font_container="tag:div|font_size:12px|text_align:left|color:%23888888|line_height:1" use_theme_fonts="yes" css=".vc_custom_1467459101263{margin-bottom: 10px !important;}" el_class="wph-secondary-font"][wph_jo_styled_textbox font_family="wph-secondary-font" custom_color="#000000"]<a href="#">Privacy Policy</a>
<a href="#">Terms of Use</a>
<a href="#">Copyright</a>[/wph_jo_styled_textbox][/vc_column][/vc_row][vc_row full_width="stretch_row" el_class="wph-secondary-bg"][vc_column][vc_empty_space height="50px" el_class="hidden-xs"][/vc_column][/vc_row][vc_row css=".vc_custom_1467226910476{padding-top: 50px !important;padding-bottom: 50px !important;}"][vc_column][vc_empty_space height="50px" el_class="hidden-xs"][vc_custom_heading text="WHAT ARE YOU THINKING ABOUT?" font_container="tag:h2|text_align:center" use_theme_fonts="yes" el_class="wph-primary-font text-italic" css=".vc_custom_1468513780723{margin-top: 0px !important;margin-bottom: 40px !important;}"][vc_column_text el_class="vertical-align-initial"]
<p class="text-center"><a class="btn btn-primary btn-lg wow fadeInLeft" href="http://demo.wphunters.com/jo/portfolio-one/">Portfolio</a> <a class="btn btn-primary btn-lg wow fadeInRight" href="http://demo.wphunters.com/jo/about/">About</a></p>
[/vc_column_text][vc_empty_space height="50px" el_class="hidden-xs"][/vc_column][/vc_row]